# TODO: proper makefile if needed

writer:	writer.cpp shmutil.cpp
	g++ -g -Wall writer.cpp shmutil.cpp -lrt -lstdc++ -o writer

reader: reader.cpp shmutil.cpp
	g++ -g -Wall reader.cpp shmutil.cpp -lrt -lstdc++ -o reader
