//
// Autogenerated by Thrift Compiler (0.16.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
if (typeof Int64 === 'undefined' && typeof require === 'function') {
  var Int64 = require('node-int64');
}


//HELPER FUNCTIONS AND STRUCTURES

JobCzar_fetchWork_args = function(args) {
  this.workerName = null;
  this.instanceName = null;
  if (args) {
    if (args.workerName !== undefined && args.workerName !== null) {
      this.workerName = args.workerName;
    }
    if (args.instanceName !== undefined && args.instanceName !== null) {
      this.instanceName = args.instanceName;
    }
  }
};
JobCzar_fetchWork_args.prototype = {};
JobCzar_fetchWork_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.workerName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.instanceName = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_fetchWork_args.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_fetchWork_args');
  if (this.workerName !== null && this.workerName !== undefined) {
    output.writeFieldBegin('workerName', Thrift.Type.STRING, 1);
    output.writeString(this.workerName);
    output.writeFieldEnd();
  }
  if (this.instanceName !== null && this.instanceName !== undefined) {
    output.writeFieldBegin('instanceName', Thrift.Type.STRING, 2);
    output.writeString(this.instanceName);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_fetchWork_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new Job(args.success);
    }
  }
};
JobCzar_fetchWork_result.prototype = {};
JobCzar_fetchWork_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new Job();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_fetchWork_result.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_fetchWork_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_submitResult_args = function(args) {
  this.result = null;
  if (args) {
    if (args.result !== undefined && args.result !== null) {
      this.result = new ResultJob(args.result);
    }
  }
};
JobCzar_submitResult_args.prototype = {};
JobCzar_submitResult_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.result = new ResultJob();
        this.result.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_submitResult_args.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_submitResult_args');
  if (this.result !== null && this.result !== undefined) {
    output.writeFieldBegin('result', Thrift.Type.STRUCT, 1);
    this.result.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_submitResult_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
JobCzar_submitResult_result.prototype = {};
JobCzar_submitResult_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_submitResult_result.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_submitResult_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_addJob_args = function(args) {
  this.agentID = null;
  this.worldID = null;
  this.agentCfg = null;
  this.worldCfg = null;
  this.priority = null;
  this.userID = null;
  this.note = null;
  if (args) {
    if (args.agentID !== undefined && args.agentID !== null) {
      this.agentID = args.agentID;
    }
    if (args.worldID !== undefined && args.worldID !== null) {
      this.worldID = args.worldID;
    }
    if (args.agentCfg !== undefined && args.agentCfg !== null) {
      this.agentCfg = args.agentCfg;
    }
    if (args.worldCfg !== undefined && args.worldCfg !== null) {
      this.worldCfg = args.worldCfg;
    }
    if (args.priority !== undefined && args.priority !== null) {
      this.priority = args.priority;
    }
    if (args.userID !== undefined && args.userID !== null) {
      this.userID = args.userID;
    }
    if (args.note !== undefined && args.note !== null) {
      this.note = args.note;
    }
  }
};
JobCzar_addJob_args.prototype = {};
JobCzar_addJob_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.agentID = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.worldID = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 3:
      if (ftype == Thrift.Type.STRING) {
        this.agentCfg = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 4:
      if (ftype == Thrift.Type.STRING) {
        this.worldCfg = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 5:
      if (ftype == Thrift.Type.I32) {
        this.priority = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 6:
      if (ftype == Thrift.Type.I32) {
        this.userID = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 7:
      if (ftype == Thrift.Type.STRING) {
        this.note = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_addJob_args.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_addJob_args');
  if (this.agentID !== null && this.agentID !== undefined) {
    output.writeFieldBegin('agentID', Thrift.Type.I32, 1);
    output.writeI32(this.agentID);
    output.writeFieldEnd();
  }
  if (this.worldID !== null && this.worldID !== undefined) {
    output.writeFieldBegin('worldID', Thrift.Type.I32, 2);
    output.writeI32(this.worldID);
    output.writeFieldEnd();
  }
  if (this.agentCfg !== null && this.agentCfg !== undefined) {
    output.writeFieldBegin('agentCfg', Thrift.Type.STRING, 3);
    output.writeString(this.agentCfg);
    output.writeFieldEnd();
  }
  if (this.worldCfg !== null && this.worldCfg !== undefined) {
    output.writeFieldBegin('worldCfg', Thrift.Type.STRING, 4);
    output.writeString(this.worldCfg);
    output.writeFieldEnd();
  }
  if (this.priority !== null && this.priority !== undefined) {
    output.writeFieldBegin('priority', Thrift.Type.I32, 5);
    output.writeI32(this.priority);
    output.writeFieldEnd();
  }
  if (this.userID !== null && this.userID !== undefined) {
    output.writeFieldBegin('userID', Thrift.Type.I32, 6);
    output.writeI32(this.userID);
    output.writeFieldEnd();
  }
  if (this.note !== null && this.note !== undefined) {
    output.writeFieldBegin('note', Thrift.Type.STRING, 7);
    output.writeString(this.note);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_addJob_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
JobCzar_addJob_result.prototype = {};
JobCzar_addJob_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.I32) {
        this.success = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_addJob_result.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_addJob_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.I32, 0);
    output.writeI32(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_fetchRunResults_args = function(args) {
  this.jobID = null;
  if (args) {
    if (args.jobID !== undefined && args.jobID !== null) {
      this.jobID = args.jobID;
    }
  }
};
JobCzar_fetchRunResults_args.prototype = {};
JobCzar_fetchRunResults_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.jobID = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_fetchRunResults_args.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_fetchRunResults_args');
  if (this.jobID !== null && this.jobID !== undefined) {
    output.writeFieldBegin('jobID', Thrift.Type.I32, 1);
    output.writeI32(this.jobID);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_fetchRunResults_result = function(args) {
};
JobCzar_fetchRunResults_result.prototype = {};
JobCzar_fetchRunResults_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_fetchRunResults_result.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_fetchRunResults_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_appendNote_args = function(args) {
  this.jobID = null;
  this.note = null;
  if (args) {
    if (args.jobID !== undefined && args.jobID !== null) {
      this.jobID = args.jobID;
    }
    if (args.note !== undefined && args.note !== null) {
      this.note = args.note;
    }
  }
};
JobCzar_appendNote_args.prototype = {};
JobCzar_appendNote_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.jobID = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.note = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_appendNote_args.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_appendNote_args');
  if (this.jobID !== null && this.jobID !== undefined) {
    output.writeFieldBegin('jobID', Thrift.Type.I32, 1);
    output.writeI32(this.jobID);
    output.writeFieldEnd();
  }
  if (this.note !== null && this.note !== undefined) {
    output.writeFieldBegin('note', Thrift.Type.STRING, 2);
    output.writeString(this.note);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_appendNote_result = function(args) {
};
JobCzar_appendNote_result.prototype = {};
JobCzar_appendNote_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_appendNote_result.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_appendNote_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_getBinInfo_args = function(args) {
  this.binID = null;
  if (args) {
    if (args.binID !== undefined && args.binID !== null) {
      this.binID = args.binID;
    }
  }
};
JobCzar_getBinInfo_args.prototype = {};
JobCzar_getBinInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.binID = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_getBinInfo_args.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_getBinInfo_args');
  if (this.binID !== null && this.binID !== undefined) {
    output.writeFieldBegin('binID', Thrift.Type.I32, 1);
    output.writeI32(this.binID);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_getBinInfo_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new BinInfo(args.success);
    }
  }
};
JobCzar_getBinInfo_result.prototype = {};
JobCzar_getBinInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new BinInfo();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_getBinInfo_result.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_getBinInfo_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_getBinInfos_args = function(args) {
};
JobCzar_getBinInfos_args.prototype = {};
JobCzar_getBinInfos_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_getBinInfos_args.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_getBinInfos_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_getBinInfos_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [BinInfo]);
    }
  }
};
JobCzar_getBinInfos_result.prototype = {};
JobCzar_getBinInfos_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        this.success = [];
        var _rtmp31 = input.readListBegin();
        var _size0 = _rtmp31.size || 0;
        for (var _i2 = 0; _i2 < _size0; ++_i2) {
          var elem3 = null;
          elem3 = new BinInfo();
          elem3.read(input);
          this.success.push(elem3);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_getBinInfos_result.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_getBinInfos_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.STRUCT, this.success.length);
    for (var iter4 in this.success) {
      if (this.success.hasOwnProperty(iter4)) {
        iter4 = this.success[iter4];
        iter4.write(output);
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_runSQL_args = function(args) {
  this.query = null;
  if (args) {
    if (args.query !== undefined && args.query !== null) {
      this.query = args.query;
    }
  }
};
JobCzar_runSQL_args.prototype = {};
JobCzar_runSQL_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.query = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_runSQL_args.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_runSQL_args');
  if (this.query !== null && this.query !== undefined) {
    output.writeFieldBegin('query', Thrift.Type.STRING, 1);
    output.writeString(this.query);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_runSQL_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
JobCzar_runSQL_result.prototype = {};
JobCzar_runSQL_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_runSQL_result.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_runSQL_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_removeJob_args = function(args) {
  this.jobID = null;
  if (args) {
    if (args.jobID !== undefined && args.jobID !== null) {
      this.jobID = args.jobID;
    }
  }
};
JobCzar_removeJob_args.prototype = {};
JobCzar_removeJob_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.jobID = input.readI32().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_removeJob_args.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_removeJob_args');
  if (this.jobID !== null && this.jobID !== undefined) {
    output.writeFieldBegin('jobID', Thrift.Type.I32, 1);
    output.writeI32(this.jobID);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_removeJob_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
JobCzar_removeJob_result.prototype = {};
JobCzar_removeJob_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_removeJob_result.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_removeJob_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_queryJobs_args = function(args) {
};
JobCzar_queryJobs_args.prototype = {};
JobCzar_queryJobs_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_queryJobs_args.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_queryJobs_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzar_queryJobs_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = Thrift.copyList(args.success, [Thrift.copyMap, null]);
    }
  }
};
JobCzar_queryJobs_result.prototype = {};
JobCzar_queryJobs_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.LIST) {
        this.success = [];
        var _rtmp36 = input.readListBegin();
        var _size5 = _rtmp36.size || 0;
        for (var _i7 = 0; _i7 < _size5; ++_i7) {
          var elem8 = null;
          elem8 = {};
          var _rtmp310 = input.readMapBegin();
          var _size9 = _rtmp310.size || 0;
          for (var _i11 = 0; _i11 < _size9; ++_i11) {
            if (_i11 > 0 ) {
              if (input.rstack.length > input.rpos[input.rpos.length -1] + 1) {
                input.rstack.pop();
              }
            }
            var key12 = null;
            var val13 = null;
            key12 = input.readString().value;
            val13 = input.readString().value;
            elem8[key12] = val13;
          }
          input.readMapEnd();
          this.success.push(elem8);
        }
        input.readListEnd();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

JobCzar_queryJobs_result.prototype.write = function(output) {
  output.writeStructBegin('JobCzar_queryJobs_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.LIST, 0);
    output.writeListBegin(Thrift.Type.MAP, this.success.length);
    for (var iter14 in this.success) {
      if (this.success.hasOwnProperty(iter14)) {
        iter14 = this.success[iter14];
        output.writeMapBegin(Thrift.Type.STRING, Thrift.Type.STRING, Thrift.objectLength(iter14));
        for (var kiter15 in iter14) {
          if (iter14.hasOwnProperty(kiter15)) {
            var viter16 = iter14[kiter15];
            output.writeString(kiter15);
            output.writeString(viter16);
          }
        }
        output.writeMapEnd();
      }
    }
    output.writeListEnd();
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

JobCzarClient = function(input, output) {
  this.input = input;
  this.output = (!output) ? input : output;
  this.seqid = 0;
};
JobCzarClient.prototype = {};

JobCzarClient.prototype.fetchWork = function(workerName, instanceName, callback) {
  this.send_fetchWork(workerName, instanceName, callback); 
  if (!callback) {
    return this.recv_fetchWork();
  }
};

JobCzarClient.prototype.send_fetchWork = function(workerName, instanceName, callback) {
  var params = {
    workerName: workerName,
    instanceName: instanceName
  };
  var args = new JobCzar_fetchWork_args(params);
  try {
    this.output.writeMessageBegin('fetchWork', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_fetchWork();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

JobCzarClient.prototype.recv_fetchWork = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new JobCzar_fetchWork_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'fetchWork failed: unknown result';
};

JobCzarClient.prototype.submitResult = function(result, callback) {
  this.send_submitResult(result, callback); 
  if (!callback) {
    return this.recv_submitResult();
  }
};

JobCzarClient.prototype.send_submitResult = function(result, callback) {
  var params = {
    result: result
  };
  var args = new JobCzar_submitResult_args(params);
  try {
    this.output.writeMessageBegin('submitResult', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_submitResult();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

JobCzarClient.prototype.recv_submitResult = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new JobCzar_submitResult_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'submitResult failed: unknown result';
};

JobCzarClient.prototype.addJob = function(agentID, worldID, agentCfg, worldCfg, priority, userID, note, callback) {
  this.send_addJob(agentID, worldID, agentCfg, worldCfg, priority, userID, note, callback); 
  if (!callback) {
    return this.recv_addJob();
  }
};

JobCzarClient.prototype.send_addJob = function(agentID, worldID, agentCfg, worldCfg, priority, userID, note, callback) {
  var params = {
    agentID: agentID,
    worldID: worldID,
    agentCfg: agentCfg,
    worldCfg: worldCfg,
    priority: priority,
    userID: userID,
    note: note
  };
  var args = new JobCzar_addJob_args(params);
  try {
    this.output.writeMessageBegin('addJob', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_addJob();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

JobCzarClient.prototype.recv_addJob = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new JobCzar_addJob_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'addJob failed: unknown result';
};

JobCzarClient.prototype.fetchRunResults = function(jobID, callback) {
  this.send_fetchRunResults(jobID, callback); 
  if (!callback) {
  this.recv_fetchRunResults();
  }
};

JobCzarClient.prototype.send_fetchRunResults = function(jobID, callback) {
  var params = {
    jobID: jobID
  };
  var args = new JobCzar_fetchRunResults_args(params);
  try {
    this.output.writeMessageBegin('fetchRunResults', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_fetchRunResults();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

JobCzarClient.prototype.recv_fetchRunResults = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new JobCzar_fetchRunResults_result();
  result.read(this.input);
  this.input.readMessageEnd();

  return;
};

JobCzarClient.prototype.appendNote = function(jobID, note, callback) {
  this.send_appendNote(jobID, note, callback); 
  if (!callback) {
  this.recv_appendNote();
  }
};

JobCzarClient.prototype.send_appendNote = function(jobID, note, callback) {
  var params = {
    jobID: jobID,
    note: note
  };
  var args = new JobCzar_appendNote_args(params);
  try {
    this.output.writeMessageBegin('appendNote', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_appendNote();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

JobCzarClient.prototype.recv_appendNote = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new JobCzar_appendNote_result();
  result.read(this.input);
  this.input.readMessageEnd();

  return;
};

JobCzarClient.prototype.getBinInfo = function(binID, callback) {
  this.send_getBinInfo(binID, callback); 
  if (!callback) {
    return this.recv_getBinInfo();
  }
};

JobCzarClient.prototype.send_getBinInfo = function(binID, callback) {
  var params = {
    binID: binID
  };
  var args = new JobCzar_getBinInfo_args(params);
  try {
    this.output.writeMessageBegin('getBinInfo', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_getBinInfo();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

JobCzarClient.prototype.recv_getBinInfo = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new JobCzar_getBinInfo_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'getBinInfo failed: unknown result';
};

JobCzarClient.prototype.getBinInfos = function(callback) {
  this.send_getBinInfos(callback); 
  if (!callback) {
    return this.recv_getBinInfos();
  }
};

JobCzarClient.prototype.send_getBinInfos = function(callback) {
  var args = new JobCzar_getBinInfos_args();
  try {
    this.output.writeMessageBegin('getBinInfos', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_getBinInfos();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

JobCzarClient.prototype.recv_getBinInfos = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new JobCzar_getBinInfos_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'getBinInfos failed: unknown result';
};

JobCzarClient.prototype.runSQL = function(query, callback) {
  this.send_runSQL(query, callback); 
  if (!callback) {
    return this.recv_runSQL();
  }
};

JobCzarClient.prototype.send_runSQL = function(query, callback) {
  var params = {
    query: query
  };
  var args = new JobCzar_runSQL_args(params);
  try {
    this.output.writeMessageBegin('runSQL', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_runSQL();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

JobCzarClient.prototype.recv_runSQL = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new JobCzar_runSQL_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'runSQL failed: unknown result';
};

JobCzarClient.prototype.removeJob = function(jobID, callback) {
  this.send_removeJob(jobID, callback); 
  if (!callback) {
    return this.recv_removeJob();
  }
};

JobCzarClient.prototype.send_removeJob = function(jobID, callback) {
  var params = {
    jobID: jobID
  };
  var args = new JobCzar_removeJob_args(params);
  try {
    this.output.writeMessageBegin('removeJob', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_removeJob();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

JobCzarClient.prototype.recv_removeJob = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new JobCzar_removeJob_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'removeJob failed: unknown result';
};

JobCzarClient.prototype.queryJobs = function(callback) {
  this.send_queryJobs(callback); 
  if (!callback) {
    return this.recv_queryJobs();
  }
};

JobCzarClient.prototype.send_queryJobs = function(callback) {
  var args = new JobCzar_queryJobs_args();
  try {
    this.output.writeMessageBegin('queryJobs', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    if (callback) {
      var self = this;
      this.output.getTransport().flush(true, function() {
        var result = null;
        try {
          result = self.recv_queryJobs();
        } catch (e) {
          result = e;
        }
        callback(result);
      });
    } else {
      return this.output.getTransport().flush();
    }
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

JobCzarClient.prototype.recv_queryJobs = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new JobCzar_queryJobs_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'queryJobs failed: unknown result';
};
