// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package worlds

const (
	Version     = "v0.0.3"
	GitCommit   = "6057e51"          // the commit JUST BEFORE the release
	VersionDate = "2022-05-26 21:32" // UTC
)
